apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: flowise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: flowise
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: nginx-ingress
  namespace: flowise
  annotations:
    kubernetes.io/ingress.class: "gce"      
    kubernetes.io/ingress.global-static-ip-name: nginxexample
    networking.gke.io/managed-certificates: managed-cert
spec:   
  rules:
  - host: dev.flow.disearch.ai
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific  
        backend:
          service:
            name: nginx-svc
            port: 
              number: 80               
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
  namespace: flowise  
spec:
  domains:
  - dev.flow.disearch.ai
